/**
 * Codes de permission RBAC de l'application, au format "MODULE:ACTION".
 *
 * Le catalogue réel vit en base (table `permissions`, seedée par
 * packages/db/prisma/seed.ts) — ces constantes ne sont qu'une référence
 * typée côté code pour éviter les fautes de frappe sur les chaînes.
 * Complété au fil des modules (Module 1 : IDENTITE).
 */
export const PERMISSION_ACTIONS = [
  "LECTURE",
  "CREATION",
  "MODIFICATION",
  "SUPPRESSION",
  "IMPRESSION",
  "EXPORT",
  "VALIDATION",
  "ADMINISTRATION",
] as const;

export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

export const PERMISSIONS = {
  UTILISATEURS_LECTURE: "UTILISATEURS:LECTURE",
  UTILISATEURS_CREATION: "UTILISATEURS:CREATION",
  UTILISATEURS_MODIFICATION: "UTILISATEURS:MODIFICATION",
  UTILISATEURS_SUPPRESSION: "UTILISATEURS:SUPPRESSION",
  UTILISATEURS_ADMINISTRATION: "UTILISATEURS:ADMINISTRATION",
  ROLES_LECTURE: "ROLES:LECTURE",
  ROLES_CREATION: "ROLES:CREATION",
  ROLES_MODIFICATION: "ROLES:MODIFICATION",
  ROLES_SUPPRESSION: "ROLES:SUPPRESSION",
  ROLES_ADMINISTRATION: "ROLES:ADMINISTRATION",
  PERMISSIONS_LECTURE: "PERMISSIONS:LECTURE",
  AUDIT_LECTURE: "AUDIT:LECTURE",
  AUDIT_EXPORT: "AUDIT:EXPORT",
  AUDIT_IMPRESSION: "AUDIT:IMPRESSION",
  PARAMETRES_SECURITE_LECTURE: "PARAMETRES_SECURITE:LECTURE",
  PARAMETRES_SECURITE_MODIFICATION: "PARAMETRES_SECURITE:MODIFICATION",

  // Module 2 — Paramètres généraux et configuration de l'établissement
  ETABLISSEMENT_LECTURE: "ETABLISSEMENT:LECTURE",
  ETABLISSEMENT_MODIFICATION: "ETABLISSEMENT:MODIFICATION",
  CAMPUS_LECTURE: "CAMPUS:LECTURE",
  CAMPUS_MODIFICATION: "CAMPUS:MODIFICATION",
  SIGNATURES_LECTURE: "SIGNATURES:LECTURE",
  SIGNATURES_MODIFICATION: "SIGNATURES:MODIFICATION",
  CACHET_LECTURE: "CACHET:LECTURE",
  CACHET_MODIFICATION: "CACHET:MODIFICATION",
  ANNEES_LECTURE: "ANNEES:LECTURE",
  ANNEES_CREATION: "ANNEES:CREATION",
  ANNEES_MODIFICATION: "ANNEES:MODIFICATION",
  ANNEES_ADMINISTRATION: "ANNEES:ADMINISTRATION",
  FILIERES_LECTURE: "FILIERES:LECTURE",
  FILIERES_CREATION: "FILIERES:CREATION",
  FILIERES_MODIFICATION: "FILIERES:MODIFICATION",
  FILIERES_SUPPRESSION: "FILIERES:SUPPRESSION",
  NIVEAUX_LECTURE: "NIVEAUX:LECTURE",
  NIVEAUX_CREATION: "NIVEAUX:CREATION",
  NIVEAUX_MODIFICATION: "NIVEAUX:MODIFICATION",
  NIVEAUX_SUPPRESSION: "NIVEAUX:SUPPRESSION",
  CLASSES_LECTURE: "CLASSES:LECTURE",
  CLASSES_CREATION: "CLASSES:CREATION",
  CLASSES_MODIFICATION: "CLASSES:MODIFICATION",
  CLASSES_SUPPRESSION: "CLASSES:SUPPRESSION",
  DEVISE_LECTURE: "DEVISE:LECTURE",
  DEVISE_MODIFICATION: "DEVISE:MODIFICATION",
  REGIONAL_LECTURE: "REGIONAL:LECTURE",
  REGIONAL_MODIFICATION: "REGIONAL:MODIFICATION",
  THEME_LECTURE: "THEME:LECTURE",
  THEME_MODIFICATION: "THEME:MODIFICATION",
  MODELES_DOCUMENTS_LECTURE: "MODELES_DOCUMENTS:LECTURE",
  MODELES_DOCUMENTS_MODIFICATION: "MODELES_DOCUMENTS:MODIFICATION",
  PARAMETRES_SAUVEGARDE_LECTURE: "PARAMETRES_SAUVEGARDE:LECTURE",
  PARAMETRES_SAUVEGARDE_VALIDATION: "PARAMETRES_SAUVEGARDE:VALIDATION",

  // Module 4 — Étudiants
  ETUDIANTS_LECTURE: "ETUDIANTS:LECTURE",
  ETUDIANTS_CREATION: "ETUDIANTS:CREATION",
  ETUDIANTS_MODIFICATION: "ETUDIANTS:MODIFICATION",
  ETUDIANTS_SUPPRESSION: "ETUDIANTS:SUPPRESSION",
  ETUDIANTS_IMPRESSION: "ETUDIANTS:IMPRESSION",
  ETUDIANTS_EXPORT: "ETUDIANTS:EXPORT",
  ETUDIANTS_ADMINISTRATION: "ETUDIANTS:ADMINISTRATION",
  ETUDIANTS_DOCUMENTS_LECTURE: "ETUDIANTS_DOCUMENTS:LECTURE",
  ETUDIANTS_DOCUMENTS_CREATION: "ETUDIANTS_DOCUMENTS:CREATION",
  ETUDIANTS_DOCUMENTS_MODIFICATION: "ETUDIANTS_DOCUMENTS:MODIFICATION",
  ETUDIANTS_DOCUMENTS_SUPPRESSION: "ETUDIANTS_DOCUMENTS:SUPPRESSION",
  ETUDIANTS_IMPORT_CREATION: "ETUDIANTS_IMPORT:CREATION",
  ETUDIANTS_IMPORT_VALIDATION: "ETUDIANTS_IMPORT:VALIDATION",

  // Module 4.1 — Inscriptions et réinscriptions
  INSCRIPTIONS_LECTURE: "INSCRIPTIONS:LECTURE",
  INSCRIPTIONS_CREATION: "INSCRIPTIONS:CREATION",
  INSCRIPTIONS_MODIFICATION: "INSCRIPTIONS:MODIFICATION",
  INSCRIPTIONS_SUPPRESSION: "INSCRIPTIONS:SUPPRESSION",
  INSCRIPTIONS_IMPRESSION: "INSCRIPTIONS:IMPRESSION",
  INSCRIPTIONS_EXPORT: "INSCRIPTIONS:EXPORT",
  INSCRIPTIONS_ADMINISTRATION: "INSCRIPTIONS:ADMINISTRATION",
  INSCRIPTIONS_IMPORT_CREATION: "INSCRIPTIONS_IMPORT:CREATION",
  INSCRIPTIONS_IMPORT_VALIDATION: "INSCRIPTIONS_IMPORT:VALIDATION",

  // Module 4.2 — Frais de scolarité
  FRAIS_LECTURE: "FRAIS:LECTURE",
  FRAIS_CREATION: "FRAIS:CREATION",
  FRAIS_MODIFICATION: "FRAIS:MODIFICATION",
  FRAIS_SUPPRESSION: "FRAIS:SUPPRESSION",
  FRAIS_EXPORT: "FRAIS:EXPORT",
  FRAIS_IMPRESSION: "FRAIS:IMPRESSION",
  FRAIS_ADMINISTRATION: "FRAIS:ADMINISTRATION",
  FRAIS_REDUCTIONS_LECTURE: "FRAIS_REDUCTIONS:LECTURE",
  FRAIS_REDUCTIONS_CREATION: "FRAIS_REDUCTIONS:CREATION",
  FRAIS_REDUCTIONS_MODIFICATION: "FRAIS_REDUCTIONS:MODIFICATION",
  FRAIS_REDUCTIONS_SUPPRESSION: "FRAIS_REDUCTIONS:SUPPRESSION",

  // Module 4.3 — Paiements et gestion de la caisse
  PAIEMENTS_LECTURE: "PAIEMENTS:LECTURE",
  PAIEMENTS_CREATION: "PAIEMENTS:CREATION",
  PAIEMENTS_SUPPRESSION: "PAIEMENTS:SUPPRESSION",
  PAIEMENTS_EXPORT: "PAIEMENTS:EXPORT",
  PAIEMENTS_IMPRESSION: "PAIEMENTS:IMPRESSION",
  PAIEMENTS_ADMINISTRATION: "PAIEMENTS:ADMINISTRATION",
  CAISSE_LECTURE: "CAISSE:LECTURE",
  CAISSE_CREATION: "CAISSE:CREATION",
  CAISSE_VALIDATION: "CAISSE:VALIDATION",
  CAISSE_ADMINISTRATION: "CAISSE:ADMINISTRATION",

  // Module 7 — Comptabilité générale et gestion financière
  COMPTABILITE_LECTURE: "COMPTABILITE:LECTURE",
  COMPTABILITE_CREATION: "COMPTABILITE:CREATION",
  COMPTABILITE_MODIFICATION: "COMPTABILITE:MODIFICATION",
  COMPTABILITE_SUPPRESSION: "COMPTABILITE:SUPPRESSION",
  ECRITURES_LECTURE: "ECRITURES:LECTURE",
  ECRITURES_CREATION: "ECRITURES:CREATION",
  ECRITURES_SUPPRESSION: "ECRITURES:SUPPRESSION",
  ECRITURES_VALIDATION: "ECRITURES:VALIDATION",
  ECRITURES_EXPORT: "ECRITURES:EXPORT",
  ECRITURES_IMPRESSION: "ECRITURES:IMPRESSION",
  DEPENSES_LECTURE: "DEPENSES:LECTURE",
  DEPENSES_CREATION: "DEPENSES:CREATION",
  DEPENSES_MODIFICATION: "DEPENSES:MODIFICATION",
  DEPENSES_SUPPRESSION: "DEPENSES:SUPPRESSION",
  DEPENSES_VALIDATION: "DEPENSES:VALIDATION",
  DEPENSES_EXPORT: "DEPENSES:EXPORT",
  DEPENSES_IMPRESSION: "DEPENSES:IMPRESSION",
  FOURNISSEURS_LECTURE: "FOURNISSEURS:LECTURE",
  FOURNISSEURS_CREATION: "FOURNISSEURS:CREATION",
  FOURNISSEURS_MODIFICATION: "FOURNISSEURS:MODIFICATION",
  FOURNISSEURS_SUPPRESSION: "FOURNISSEURS:SUPPRESSION",
  BUDGET_LECTURE: "BUDGET:LECTURE",
  BUDGET_CREATION: "BUDGET:CREATION",
  BUDGET_MODIFICATION: "BUDGET:MODIFICATION",
  BUDGET_SUPPRESSION: "BUDGET:SUPPRESSION",
  RAPPORTS_FINANCIERS_LECTURE: "RAPPORTS_FINANCIERS:LECTURE",
  RAPPORTS_FINANCIERS_EXPORT: "RAPPORTS_FINANCIERS:EXPORT",
  RAPPORTS_FINANCIERS_IMPRESSION: "RAPPORTS_FINANCIERS:IMPRESSION",

  // Module 2.1 — Structure pédagogique
  MATIERES_LECTURE: "MATIERES:LECTURE",
  MATIERES_CREATION: "MATIERES:CREATION",
  MATIERES_MODIFICATION: "MATIERES:MODIFICATION",
  MATIERES_SUPPRESSION: "MATIERES:SUPPRESSION",
  MATIERES_EXPORT: "MATIERES:EXPORT",
  MATIERES_IMPRESSION: "MATIERES:IMPRESSION",
  MATIERES_ADMINISTRATION: "MATIERES:ADMINISTRATION",
  MATIERES_IMPORT_CREATION: "MATIERES_IMPORT:CREATION",
  MATIERES_IMPORT_VALIDATION: "MATIERES_IMPORT:VALIDATION",

  // Module 2.1 — permissions additives (Module 2, années/filières/niveaux/classes)
  ANNEES_EXPORT: "ANNEES:EXPORT",
  ANNEES_IMPRESSION: "ANNEES:IMPRESSION",
  FILIERES_EXPORT: "FILIERES:EXPORT",
  FILIERES_IMPRESSION: "FILIERES:IMPRESSION",
  NIVEAUX_EXPORT: "NIVEAUX:EXPORT",
  NIVEAUX_IMPRESSION: "NIVEAUX:IMPRESSION",
  CLASSES_EXPORT: "CLASSES:EXPORT",
  CLASSES_IMPRESSION: "CLASSES:IMPRESSION",

  // Module 5 — Gestion des enseignants
  ENSEIGNANTS_LECTURE: "ENSEIGNANTS:LECTURE",
  ENSEIGNANTS_CREATION: "ENSEIGNANTS:CREATION",
  ENSEIGNANTS_MODIFICATION: "ENSEIGNANTS:MODIFICATION",
  ENSEIGNANTS_SUPPRESSION: "ENSEIGNANTS:SUPPRESSION",
  ENSEIGNANTS_EXPORT: "ENSEIGNANTS:EXPORT",
  ENSEIGNANTS_IMPRESSION: "ENSEIGNANTS:IMPRESSION",
  ENSEIGNANTS_ADMINISTRATION: "ENSEIGNANTS:ADMINISTRATION",
  ENSEIGNANTS_AFFECTATIONS_LECTURE: "ENSEIGNANTS_AFFECTATIONS:LECTURE",
  ENSEIGNANTS_AFFECTATIONS_CREATION: "ENSEIGNANTS_AFFECTATIONS:CREATION",
  ENSEIGNANTS_AFFECTATIONS_MODIFICATION: "ENSEIGNANTS_AFFECTATIONS:MODIFICATION",
  ENSEIGNANTS_AFFECTATIONS_SUPPRESSION: "ENSEIGNANTS_AFFECTATIONS:SUPPRESSION",
  ENSEIGNANTS_DOCUMENTS_LECTURE: "ENSEIGNANTS_DOCUMENTS:LECTURE",
  ENSEIGNANTS_DOCUMENTS_CREATION: "ENSEIGNANTS_DOCUMENTS:CREATION",
  ENSEIGNANTS_DOCUMENTS_MODIFICATION: "ENSEIGNANTS_DOCUMENTS:MODIFICATION",
  ENSEIGNANTS_DOCUMENTS_SUPPRESSION: "ENSEIGNANTS_DOCUMENTS:SUPPRESSION",

  // Module 8 — Paie
  PAIE_LECTURE: "PAIE:LECTURE",
  PAIE_ADMINISTRATION: "PAIE:ADMINISTRATION",
  PAIE_EMPLOYES_LECTURE: "PAIE_EMPLOYES:LECTURE",
  PAIE_EMPLOYES_CREATION: "PAIE_EMPLOYES:CREATION",
  PAIE_EMPLOYES_MODIFICATION: "PAIE_EMPLOYES:MODIFICATION",
  PAIE_EMPLOYES_SUPPRESSION: "PAIE_EMPLOYES:SUPPRESSION",
  PAIE_EMPLOYES_EXPORT: "PAIE_EMPLOYES:EXPORT",
  PAIE_EMPLOYES_IMPRESSION: "PAIE_EMPLOYES:IMPRESSION",
  PAIE_BULLETINS_LECTURE: "PAIE_BULLETINS:LECTURE",
  PAIE_BULLETINS_CREATION: "PAIE_BULLETINS:CREATION",
  PAIE_BULLETINS_MODIFICATION: "PAIE_BULLETINS:MODIFICATION",
  PAIE_BULLETINS_VALIDATION: "PAIE_BULLETINS:VALIDATION",
  PAIE_BULLETINS_IMPRESSION: "PAIE_BULLETINS:IMPRESSION",
  PAIE_AVANCES_LECTURE: "PAIE_AVANCES:LECTURE",
  PAIE_AVANCES_CREATION: "PAIE_AVANCES:CREATION",
  PAIE_AVANCES_MODIFICATION: "PAIE_AVANCES:MODIFICATION",
  PAIE_AVANCES_SUPPRESSION: "PAIE_AVANCES:SUPPRESSION",

  // Module 5.1 — Pointage des enseignants
  POINTAGE_LECTURE: "POINTAGE:LECTURE",
  POINTAGE_MODIFICATION: "POINTAGE:MODIFICATION",
  POINTAGE_VALIDATION: "POINTAGE:VALIDATION",
  POINTAGE_ADMINISTRATION: "POINTAGE:ADMINISTRATION",

  // Module 6 — Évaluation (notes, bulletins, classement)
  NOTES_LECTURE: "NOTES:LECTURE",
  NOTES_MODIFICATION: "NOTES:MODIFICATION",
  NOTES_ADMINISTRATION: "NOTES:ADMINISTRATION",
  BULLETINS_LECTURE: "BULLETINS:LECTURE",
  BULLETINS_CREATION: "BULLETINS:CREATION",
  BULLETINS_ADMINISTRATION: "BULLETINS:ADMINISTRATION",
  CLASSEMENT_LECTURE: "CLASSEMENT:LECTURE",
  EVALUATION_ADMINISTRATION: "EVALUATION:ADMINISTRATION",

  // Module 5.2 — Emploi du temps et pointage pédagogique
  EMPLOI_DU_TEMPS_LECTURE: "EMPLOI_DU_TEMPS:LECTURE",
  EMPLOI_DU_TEMPS_MODIFICATION: "EMPLOI_DU_TEMPS:MODIFICATION",
  EMPLOI_DU_TEMPS_ADMINISTRATION: "EMPLOI_DU_TEMPS:ADMINISTRATION",
  SALLES_LECTURE: "SALLES:LECTURE",
  SALLES_MODIFICATION: "SALLES:MODIFICATION",
  GROUPES_PEDAGOGIQUES_LECTURE: "GROUPES_PEDAGOGIQUES:LECTURE",
  GROUPES_PEDAGOGIQUES_MODIFICATION: "GROUPES_PEDAGOGIQUES:MODIFICATION",

  // Module 12 — Centre de Communication Intelligent
  COMMUNICATION_LECTURE: "COMMUNICATION:LECTURE",
  COMMUNICATION_CREATION: "COMMUNICATION:CREATION",
  CAMPAGNES_LECTURE: "CAMPAGNES:LECTURE",
  CAMPAGNES_CREATION: "CAMPAGNES:CREATION",
  CAMPAGNES_MODIFICATION: "CAMPAGNES:MODIFICATION",
  CAMPAGNES_SUPPRESSION: "CAMPAGNES:SUPPRESSION",
  CAMPAGNES_VALIDATION: "CAMPAGNES:VALIDATION",
  MODELES_COMMUNICATION_LECTURE: "MODELES_COMMUNICATION:LECTURE",
  MODELES_COMMUNICATION_MODIFICATION: "MODELES_COMMUNICATION:MODIFICATION",
  PARAMETRES_COMMUNICATION_LECTURE: "PARAMETRES_COMMUNICATION:LECTURE",
  PARAMETRES_COMMUNICATION_MODIFICATION: "PARAMETRES_COMMUNICATION:MODIFICATION",

  // Module 9 — Moteur centralisé de documents officiels
  DOCUMENTS_LECTURE: "DOCUMENTS:LECTURE",
  DOCUMENTS_CREATION: "DOCUMENTS:CREATION",
  DOCUMENTS_ADMINISTRATION: "DOCUMENTS:ADMINISTRATION",
  PARAMETRES_DOCUMENTS_LECTURE: "PARAMETRES_DOCUMENTS:LECTURE",
  PARAMETRES_DOCUMENTS_MODIFICATION: "PARAMETRES_DOCUMENTS:MODIFICATION",

  // Sanctions disciplinaires (2026-08-03, retour du porteur du projet)
  SANCTIONS_LECTURE: "SANCTIONS:LECTURE",
  SANCTIONS_CREATION: "SANCTIONS:CREATION",
  SANCTIONS_ADMINISTRATION: "SANCTIONS:ADMINISTRATION",

  // Absences des étudiants (2026-08-03, retour du porteur du projet)
  ABSENCES_LECTURE: "ABSENCES:LECTURE",
  ABSENCES_CREATION: "ABSENCES:CREATION",
  ABSENCES_SUPPRESSION: "ABSENCES:SUPPRESSION",

  // Sessionnaires / sessions de rattrapage (2026-08-03, retour du porteur du projet)
  SESSIONNAIRES_LECTURE: "SESSIONNAIRES:LECTURE",
  SESSIONNAIRES_CREATION: "SESSIONNAIRES:CREATION",
  SESSIONNAIRES_SUPPRESSION: "SESSIONNAIRES:SUPPRESSION",

  // Module 10 — Tableau de bord & Rapports décisionnels
  RAPPORTS_DECISIONNELS_LECTURE: "RAPPORTS_DECISIONNELS:LECTURE",
  ALERTES_LECTURE: "ALERTES:LECTURE",
  ALERTES_MODIFICATION: "ALERTES:MODIFICATION",

  // Module 11 — Sauvegarde, Sécurité avancée, Audit
  SAUVEGARDE_BDD_LECTURE: "SAUVEGARDE_BDD:LECTURE",
  SAUVEGARDE_BDD_CREATION: "SAUVEGARDE_BDD:CREATION",
  SAUVEGARDE_BDD_MODIFICATION: "SAUVEGARDE_BDD:MODIFICATION",
  SAUVEGARDE_BDD_ADMINISTRATION: "SAUVEGARDE_BDD:ADMINISTRATION",

  // Module 14 — Inventaire
  INVENTAIRE_LECTURE: "INVENTAIRE:LECTURE",
  INVENTAIRE_CREATION: "INVENTAIRE:CREATION",
  INVENTAIRE_MODIFICATION: "INVENTAIRE:MODIFICATION",
  INVENTAIRE_SUPPRESSION: "INVENTAIRE:SUPPRESSION",
  INVENTAIRE_ADMINISTRATION: "INVENTAIRE:ADMINISTRATION",

  // Module 13 — Bibliothèque
  BIBLIOTHEQUE_LECTURE: "BIBLIOTHEQUE:LECTURE",
  BIBLIOTHEQUE_CREATION: "BIBLIOTHEQUE:CREATION",
  BIBLIOTHEQUE_MODIFICATION: "BIBLIOTHEQUE:MODIFICATION",
  BIBLIOTHEQUE_SUPPRESSION: "BIBLIOTHEQUE:SUPPRESSION",
  BIBLIOTHEQUE_ADMINISTRATION: "BIBLIOTHEQUE:ADMINISTRATION",

  // Module 13 (extension) — Bibliothèque numérique
  BIBLIOTHEQUE_NUMERIQUE_LECTURE: "BIBLIOTHEQUE_NUMERIQUE:LECTURE",
  BIBLIOTHEQUE_NUMERIQUE_CREATION: "BIBLIOTHEQUE_NUMERIQUE:CREATION",
  BIBLIOTHEQUE_NUMERIQUE_SUPPRESSION: "BIBLIOTHEQUE_NUMERIQUE:SUPPRESSION",
  BIBLIOTHEQUE_NUMERIQUE_ADMINISTRATION: "BIBLIOTHEQUE_NUMERIQUE:ADMINISTRATION",

  // Module 15 — Portail web (gestion des comptes externes côté personnel — le portail lui-même
  // n'utilise jamais le RBAC, voir MODULE-15 §2.1)
  PORTAIL_WEB_LECTURE: "PORTAIL_WEB:LECTURE",
  PORTAIL_WEB_CREATION: "PORTAIL_WEB:CREATION",
  PORTAIL_WEB_ADMINISTRATION: "PORTAIL_WEB:ADMINISTRATION",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Rôle dont le code porte implicitement toutes les permissions (voir MODULE-01 §3.3). */
export const SUPER_ADMIN_ROLE_CODE = "SUPER_ADMIN";
